### ISSUE TITLE
(grisbi:2): Gtk-WARNING **: cannot open display:

### ISSUE THREAD

**Issue by lameute76** [flathub/org.grisbi.Grisbi#5]
Hello,

since a few days i have this problem on grisbi launching:

`(grisbi:2): Gtk-WARNING **: 19:42:36.702: cannot open display: `

Wayland problem ?

Grisbi is installed from flathub.

Thank you for all.

**Comment by abompard** [comment]
This should be fixed by e5a3183, I'm not sure why the previous version ever worked on my computer... :-/
The update should appear on Flathub shortly.
